export const initialPlaces = [
  {
    id: "p1",
    name: "Mirador de la Laguna de Xiloá",
    category: "naturaleza",
    description: "Punto panorámico para observar la laguna y tomar fotografías al atardecer.",
    lat: 12.2476,
    lng: -86.3301,
    imageUrl: "https://images.unsplash.com/photo-1537111261222-6b50f4f54f7f?auto=format&fit=crop&w=1200&q=80",
    tags: ["Mirador", "Paisaje"]
  },
  {
    id: "p2",
    name: "Sendero Ecológico Cuajachillo",
    category: "aventura",
    description: "Recorrido guiado por bosque seco tropical con avistamiento de aves.",
    lat: 12.2558,
    lng: -86.4232,
    imageUrl: "https://images.unsplash.com/photo-1482192505345-5655af888cc4?auto=format&fit=crop&w=1200&q=80",
    tags: ["Senderismo", "Aventura"]
  },
  {
    id: "p3",
    name: "Centro Cultural de Mateare",
    category: "cultura",
    description: "Espacio comunitario con expresiones artísticas, danza y gastronomía local.",
    lat: 12.2424,
    lng: -86.4318,
    imageUrl: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80",
    tags: ["Cultura", "Comunidad"]
  }
];

export const initialServices = [
  {
    id: "s1",
    name: "Comedor Doña Martha",
    type: "alimentacion",
    contact: "+505 8888 1234",
    schedule: "7:00 AM - 7:00 PM"
  },
  {
    id: "s2",
    name: "Hostal Brisa de Xiloá",
    type: "hospedaje",
    contact: "+505 8787 6767",
    schedule: "24 horas"
  }
];

export const initialAlerts = [
  {
    id: "a1",
    level: "medium",
    title: {
      es: "Recomendación de hidratación",
      en: "Hydration advisory"
    },
    description: {
      es: "Temperaturas altas entre las 12:00 y 15:00. Lleva agua y bloqueador solar.",
      en: "High temperatures from 12:00 to 15:00. Carry water and sunscreen."
    }
  },
  {
    id: "a2",
    level: "high",
    title: {
      es: "Precaución por lluvias",
      en: "Heavy rain caution"
    },
    description: {
      es: "Posibles lluvias por la tarde en rutas rurales. Verifica el estado de caminos.",
      en: "Possible afternoon rain on rural routes. Check road conditions."
    }
  }
];

// Reemplaza estas URLs por tus propias fotos cuando las subas.
export const heroBackgroundImages = [
  "mateare1.jpeg",
  "mateare2.jpeg",
  "mateare3.jpeg",
  "Mateare_Barco.jpg"
];

export const i18n = {
  es: {
    "nav.home": "Inicio",
    "nav.diagnosis": "Diagnóstico",
    "nav.guides": "Guías",
    "nav.register": "Publicar",
    "nav.map": "Mapa y Rutas",
    "nav.moderation": "Moderación",
    "nav.contact": "Contacto",
    "auth.guest": "Invitado",
    "auth.signIn": "Entrar con Google",
    "auth.signOut": "Salir",
    "auth.required": "Inicia sesión con Google para publicar lugares y servicios.",
    "auth.connectedAs": "Conectado como",
    "auth.firebaseOff": "Modo local activo: completa firebase-config.js para activar Firebase.",
    "hero.tag": "Turismo comunitario en Nicaragua",
    "hero.title": "Descubre Mateare con rutas, guías y servicios locales",
    "hero.description": "Plataforma digital para turistas nacionales y extranjeros que conecta emprendimientos, lugares turísticos poco difundidos y experiencias auténticas en el municipio de Mateare.",
    "hero.primaryCta": "Explorar destinos",
    "hero.secondaryCta": "Publicar emprendimiento",
    "hero.panelTitle": "Estado rápido del destino",
    "hero.weather": "Clima actual",
    "hero.alerts": "Alertas activas",
    "hero.posts": "Publicaciones comunitarias",
    "diagnosis.tag": "Diagnóstico territorial",
    "diagnosis.title": "Digitalizar para visibilizar el turismo local",
    "diagnosis.description": "El municipio cuenta con atractivos naturales, cultura viva y emprendimientos gastronómicos, pero su difusión digital es limitada. Este portal centraliza información y fortalece la promoción turística.",
    "diagnosis.card1.title": "Baja promoción",
    "diagnosis.card1.text": "Muchos destinos y servicios no tienen presencia web constante.",
    "diagnosis.card2.title": "Necesidad de rutas",
    "diagnosis.card2.text": "El turista requiere orientación clara para llegar de forma segura y rápida.",
    "diagnosis.card3.title": "Oportunidad económica",
    "diagnosis.card3.text": "La digitalización impulsa emprendedores y dinamiza la economía local.",
    "guides.tag": "Guía turística dinámica",
    "guides.title": "Lugares recomendados en Mateare",
    "guides.searchLabel": "Buscar",
    "guides.searchPlaceholder": "Ej: Mirador",
    "guides.filterLabel": "Categoría",
    "guides.all": "Todas",
    "guides.nature": "Naturaleza",
    "guides.culture": "Cultura",
    "guides.adventure": "Aventura",
    "weather.tag": "Clima en tiempo real",
    "weather.title": "Consulta el estado climático",
    "weather.destination": "Destino",
    "weather.refresh": "Actualizar",
    "weather.loading": "Cargando clima...",
    "weather.condition": "Condición",
    "weather.period": "Momento",
    "weather.periodDay": "Día",
    "weather.periodNight": "Noche",
    "weather.suggestion": "Sugerencia",
    "weather.condition.clear": "Despejado",
    "weather.condition.partlyCloudy": "Parcialmente nublado",
    "weather.condition.cloudy": "Nublado",
    "weather.condition.fog": "Neblina",
    "weather.condition.drizzle": "Llovizna",
    "weather.condition.rain": "Lluvia",
    "weather.condition.storm": "Tormenta",
    "weather.suggestion.sunDay": "Excelente para recorrer miradores. Lleva agua y protector solar.",
    "weather.suggestion.clearNight": "Noche tranquila para actividades cortas. Usa ropa ligera y mantente en rutas seguras.",
    "weather.suggestion.rain": "Lleva paraguas o capa y calzado antideslizante para senderos.",
    "weather.suggestion.wind": "Hay viento fuerte. Evita zonas abiertas y asegura gorra o sombrero.",
    "weather.suggestion.heat": "Calor intenso. Hidratarse cada 30 minutos y preferir sombra.",
    "weather.suggestion.coolNight": "Temperatura fresca de noche. Lleva suéter ligero.",
    "weather.suggestion.cloudy": "Clima estable para paseos. Ideal para rutas culturales y gastronomía local.",
    "alerts.tag": "Sistema de alertas",
    "alerts.title": "Información útil para viajar",
    "alerts.readMore": "Leer noticia",
    "alerts.sync.never": "Sin sincronización reciente de noticias.",
    "alerts.sync.loading": "Buscando noticias recientes...",
    "alerts.sync.updated": "Última actualización",
    "alerts.sync.error": "No se pudo actualizar noticias en este momento.",
    "alerts.sync.noRecent": "No se encontraron noticias recientes; se muestran alertas de respaldo.",
    "publish.tag": "Registro comunitario",
    "publish.title": "Publica lugares y servicios turísticos",
    "publish.placeTitle": "Registrar lugar turístico",
    "publish.placeName": "Nombre del lugar",
    "publish.placeCategory": "Categoría",
    "publish.description": "Descripción",
    "publish.placeImageUrls": "URLs de imagen (opcional)",
    "publish.placeImageUrlsPlaceholder": "https://... (una por línea o separadas por coma)",
    "publish.placeImageFiles": "Subir imágenes (opcional)",
    "publish.pickOnMap": "Seleccionar en mapa",
    "publish.clearLocation": "Limpiar ubicación",
    "publish.locationHint": "Haz clic en \"Seleccionar en mapa\" y luego toca el punto exacto en el mapa.",
    "publish.publishPlace": "Publicar lugar",
    "publish.serviceTitle": "Registrar servicio turístico",
    "publish.serviceName": "Nombre del servicio",
    "publish.serviceType": "Tipo",
    "publish.food": "Alimentación",
    "publish.lodging": "Hospedaje",
    "publish.activities": "Actividades",
    "publish.contact": "Contacto",
    "publish.schedule": "Horario",
    "publish.serviceImageUrls": "URLs de imagen (opcional)",
    "publish.serviceImageUrlsPlaceholder": "https://... (una por línea o separadas por coma)",
    "publish.serviceImageFiles": "Subir imágenes (opcional)",
    "publish.publishService": "Publicar servicio",
    "publish.feedTitle": "Publicaciones comunitarias",
    "map.tag": "Ubicación y rutas",
    "map.title": "Mapa interactivo de destinos",
    "map.viewCard": "Ver tarjeta",
    "admin.tag": "Panel administrativo",
    "admin.title": "Moderar publicaciones pendientes",
    "admin.description": "Aprueba, rechaza o elimina el contenido enviado por la comunidad.",
    "admin.pendingPlaces": "Lugares pendientes",
    "admin.pendingServices": "Servicios pendientes",
    "admin.managePlaces": "Gestionar lugares",
    "admin.manageServices": "Gestionar servicios",
    "admin.emptyPlaces": "No hay lugares pendientes por revisar.",
    "admin.emptyServices": "No hay servicios pendientes por revisar.",
    "admin.emptyAllPlaces": "No hay lugares registrados.",
    "admin.emptyAllServices": "No hay servicios registrados.",
    "admin.approve": "Aprobar",
    "admin.reject": "Rechazar",
    "admin.edit": "Editar",
    "admin.delete": "Eliminar",
    "admin.createdBy": "Creado por",
    "admin.statusPending": "Pendiente",
    "admin.statusApproved": "Aprobado",
    "admin.statusRejected": "Rechazado",
    "admin.editorTitle": "Editor administrativo",
    "admin.editorName": "Nombre",
    "admin.editorImages": "URLs de imágenes",
    "admin.editorImageFiles": "Subir imágenes nuevas (opcional)",
    "admin.editorStatus": "Estado",
    "admin.saveChanges": "Guardar cambios",
    "admin.cancelEdit": "Cancelar",
    "footer.text": "Mateare Vivo - Turismo comunitario - Compatible con Android, iOS y Windows",
    "footer.links": "Enlaces rápidos",
    "footer.contact": "Contacto local",
    "footer.contactText": "Promoción turística comunitaria de Mateare, Managua.",
    "guide.route": "Trazar ruta",
    "guide.more": "Ver en mapa",
    "guide.category": "Categoría",
    "weather.temp": "Temperatura",
    "weather.wind": "Viento",
    "weather.rain": "Lluvia",
    "weather.updated": "Actualizado",
    "weather.error": "No se pudo cargar el clima en este momento.",
    "feed.place": "Nuevo lugar",
    "feed.service": "Nuevo servicio",
    "alert.none": "No hay alertas activas por ahora.",
    "msg.placeSaved": "Lugar publicado correctamente.",
    "msg.placePending": "Tu lugar fue enviado para revisión del administrador.",
    "msg.placeSaveError": "No se pudo publicar el lugar. Intenta de nuevo.",
    "msg.serviceSaved": "Servicio publicado correctamente.",
    "msg.servicePending": "Tu servicio fue enviado para revisión del administrador.",
    "msg.serviceSaveError": "No se pudo publicar el servicio. Intenta de nuevo.",
    "msg.permissionDenied": "No tienes permisos para esta acción. Revisa reglas y autenticación.",
    "msg.invalidImage": "La URL de imagen no es valida.",
    "msg.imageUploadError": "No se pudieron subir una o más imágenes. Verifica formato, tamaño, conexión y permisos de Firebase Storage.",
    "msg.imageUploadPartial": "El negocio se guardó, pero algunas imágenes no se pudieron subir.",
    "msg.realtimeSync": "Actualización en tiempo real recibida.",
    "msg.signInRequired": "Debes iniciar sesión con Google para publicar. Si no has iniciado sesión, el botón de publicar no enviará datos.",
    "msg.firebaseLoadError": "No fue posible cargar datos en tiempo real.",
    "msg.signInError": "No se pudo iniciar sesión con Google.",
    "msg.signInBlockedDomain": "Este dominio no esta autorizado en Firebase Auth. Agrega harinrc.github.io en Authorized domains.",
    "msg.signInPopupBlocked": "El navegador bloqueo la ventana emergente de Google. Permite popups e intenta de nuevo.",
    "msg.signInPopupClosed": "Cerraste la ventana de inicio de sesión antes de completar el proceso.",
    "msg.signInOperationDisabled": "Google Sign-In no esta habilitado en Firebase Authentication.",
    "msg.signInNetworkError": "Error de red al iniciar sesión. Verifica conexión e intenta otra vez.",
    "msg.adminOnly": "Esta acción es solo para administradores.",
    "msg.moderationUpdated": "Moderación aplicada correctamente.",
    "msg.moderationError": "No se pudo aplicar la moderación.",
    "msg.editorSaved": "Cambios guardados correctamente.",
    "msg.mapPickStart": "Selecciona el punto en el mapa para guardar la ubicación.",
    "msg.mapLocationSet": "Ubicación cargada desde el mapa.",
    "msg.mapLocationCleared": "Ubicación limpiada.",
    "msg.locationRequired": "Debes seleccionar una ubicación en el mapa antes de publicar.",
    "install.title": "Instala Mateare Vivo",
    "install.description": "Agrega la app a tu dispositivo para abrirla rápido y usarla con acceso más cómodo desde el móvil.",
    "install.descriptionUnsupported": "Tu navegador no ofrece instalación automática aquí, pero aún puedes usar la web o abrirla en un navegador compatible para instalarla.",
    "install.cta": "Instalar app",
    "install.ctaHelp": "Ver cómo instalar",
    "install.dismiss": "Ahora no",
    "install.ready": "La app está lista para instalarse en tu dispositivo.",
    "install.success": "Mateare Vivo se instaló correctamente.",
    "install.unavailable": "La instalación no está disponible en este navegador por ahora. Usa Chrome o Edge en Android para verla.",
    "install.unavailableDesktop": "La instalación automática no está disponible en este navegador de escritorio. Usa Chrome o Edge actualizado.",
    "install.unavailableMobile": "La instalación automática no está disponible en este navegador móvil. Prueba con Chrome en Android.",
    "install.iosInstructions": "En iPhone/iPad: abre Compartir y elige \"Añadir a pantalla de inicio\" para instalar la app.",
    "install.notSupported": "Tu navegador ya muestra esta app como instalada o no admite instalación.",
    "install.notNow": "Está bien, te lo volveré a mostrar más adelante.",
    "gallery.title": "Vista previa",
    "gallery.prev": "Anterior",
    "gallery.next": "Siguiente",
    "gallery.zoomIn": "Acercar",
    "gallery.zoomOut": "Alejar",
    "gallery.reset": "Reiniciar",
    "gallery.close": "Cerrar",
    "gallery.hint": "Consejo: puedes acercar y alejar para ver detalles."
  },
  en: {
    "nav.home": "Home",
    "nav.diagnosis": "Diagnosis",
    "nav.guides": "Guides",
    "nav.register": "Publish",
    "nav.map": "Map and Routes",
    "nav.moderation": "Moderation",
    "nav.contact": "Contact",
    "auth.guest": "Guest",
    "auth.signIn": "Sign in with Google",
    "auth.signOut": "Sign out",
    "auth.required": "Sign in with Google to publish places and services.",
    "auth.connectedAs": "Connected as",
    "auth.firebaseOff": "Local mode enabled: fill firebase-config.js to activate Firebase.",
    "hero.tag": "Community tourism in Nicaragua",
    "hero.title": "Discover Mateare with routes, guides, and local services",
    "hero.description": "Digital platform for national and international tourists that connects entrepreneurs, under-promoted attractions, and authentic experiences in Mateare.",
    "hero.primaryCta": "Explore destinations",
    "hero.secondaryCta": "Publish business",
    "hero.panelTitle": "Quick destination status",
    "hero.weather": "Current weather",
    "hero.alerts": "Active alerts",
    "hero.posts": "Community posts",
    "diagnosis.tag": "Territorial diagnosis",
    "diagnosis.title": "Digitize to make local tourism visible",
    "diagnosis.description": "The municipality has natural attractions, living culture, and gastronomy ventures, but digital promotion is still limited. This portal centralizes information and strengthens tourism promotion.",
    "diagnosis.card1.title": "Low promotion",
    "diagnosis.card1.text": "Many destinations and services lack consistent web presence.",
    "diagnosis.card2.title": "Route guidance needed",
    "diagnosis.card2.text": "Tourists need clear orientation to arrive safely and quickly.",
    "diagnosis.card3.title": "Economic opportunity",
    "diagnosis.card3.text": "Digitization boosts entrepreneurs and local economy.",
    "guides.tag": "Dynamic tourism guide",
    "guides.title": "Recommended places in Mateare",
    "guides.searchLabel": "Search",
    "guides.searchPlaceholder": "Ex: Viewpoint",
    "guides.filterLabel": "Category",
    "guides.all": "All",
    "guides.nature": "Nature",
    "guides.culture": "Culture",
    "guides.adventure": "Adventure",
    "weather.tag": "Real-time weather",
    "weather.title": "Check live weather conditions",
    "weather.destination": "Destination",
    "weather.refresh": "Refresh",
    "weather.loading": "Loading weather...",
    "weather.condition": "Condition",
    "weather.period": "Period",
    "weather.periodDay": "Day",
    "weather.periodNight": "Night",
    "weather.suggestion": "Suggestion",
    "weather.condition.clear": "Clear",
    "weather.condition.partlyCloudy": "Partly cloudy",
    "weather.condition.cloudy": "Cloudy",
    "weather.condition.fog": "Fog",
    "weather.condition.drizzle": "Drizzle",
    "weather.condition.rain": "Rain",
    "weather.condition.storm": "Storm",
    "weather.suggestion.sunDay": "Great for viewpoints. Bring water and sunscreen.",
    "weather.suggestion.clearNight": "Calm night for short activities. Wear light layers and stay on safe routes.",
    "weather.suggestion.rain": "Bring an umbrella or rain jacket and non-slip shoes for trails.",
    "weather.suggestion.wind": "Strong wind conditions. Avoid exposed areas and secure hats.",
    "weather.suggestion.heat": "High heat. Hydrate every 30 minutes and seek shade.",
    "weather.suggestion.coolNight": "Cool night temperatures. Bring a light sweater.",
    "weather.suggestion.cloudy": "Stable weather for walks. Great for cultural routes and local food.",
    "alerts.tag": "Alert system",
    "alerts.title": "Useful travel info",
    "alerts.readMore": "Read article",
    "alerts.sync.never": "No recent news sync yet.",
    "alerts.sync.loading": "Checking recent news...",
    "alerts.sync.updated": "Last update",
    "alerts.sync.error": "Could not refresh news right now.",
    "alerts.sync.noRecent": "No recent articles found; showing fallback alerts.",
    "publish.tag": "Community publishing",
    "publish.title": "Publish attractions and tourism services",
    "publish.placeTitle": "Register tourist place",
    "publish.placeName": "Place name",
    "publish.placeCategory": "Category",
    "publish.description": "Description",
    "publish.placeImageUrls": "Image URLs (optional)",
    "publish.placeImageUrlsPlaceholder": "https://... (one per line or comma-separated)",
    "publish.placeImageFiles": "Upload images (optional)",
    "publish.pickOnMap": "Pick on map",
    "publish.clearLocation": "Clear location",
    "publish.locationHint": "Click \"Pick on map\" and then tap the exact point on the map.",
    "publish.publishPlace": "Publish place",
    "publish.serviceTitle": "Register tourism service",
    "publish.serviceName": "Service name",
    "publish.serviceType": "Type",
    "publish.food": "Food",
    "publish.lodging": "Lodging",
    "publish.activities": "Activities",
    "publish.contact": "Contact",
    "publish.schedule": "Schedule",
    "publish.serviceImageUrls": "Image URLs (optional)",
    "publish.serviceImageUrlsPlaceholder": "https://... (one per line or comma-separated)",
    "publish.serviceImageFiles": "Upload images (optional)",
    "publish.publishService": "Publish service",
    "publish.feedTitle": "Community publications",
    "map.tag": "Location and routes",
    "map.title": "Interactive destination map",
    "map.viewCard": "View card",
    "admin.tag": "Admin panel",
    "admin.title": "Moderate pending submissions",
    "admin.description": "Approve, reject, or delete content submitted by the community.",
    "admin.pendingPlaces": "Pending places",
    "admin.pendingServices": "Pending services",
    "admin.managePlaces": "Manage places",
    "admin.manageServices": "Manage services",
    "admin.emptyPlaces": "No pending places to review.",
    "admin.emptyServices": "No pending services to review.",
    "admin.emptyAllPlaces": "No places registered yet.",
    "admin.emptyAllServices": "No services registered yet.",
    "admin.approve": "Approve",
    "admin.reject": "Reject",
    "admin.edit": "Edit",
    "admin.delete": "Delete",
    "admin.createdBy": "Created by",
    "admin.statusPending": "Pending",
    "admin.statusApproved": "Approved",
    "admin.statusRejected": "Rejected",
    "admin.editorTitle": "Admin editor",
    "admin.editorName": "Name",
    "admin.editorImages": "Image URLs",
    "admin.editorImageFiles": "Upload new images (optional)",
    "admin.editorStatus": "Status",
    "admin.saveChanges": "Save changes",
    "admin.cancelEdit": "Cancel",
    "footer.text": "Mateare Vivo - Community tourism - Compatible with Android, iOS and Windows",
    "footer.links": "Quick links",
    "footer.contact": "Local contact",
    "footer.contactText": "Community tourism promotion in Mateare, Managua.",
    "guide.route": "Get directions",
    "guide.more": "View on map",
    "guide.category": "Category",
    "weather.temp": "Temperature",
    "weather.wind": "Wind",
    "weather.rain": "Rain",
    "weather.updated": "Updated",
    "weather.error": "Weather could not be loaded at this time.",
    "feed.place": "New place",
    "feed.service": "New service",
    "alert.none": "No active alerts right now.",
    "msg.placeSaved": "Place published successfully.",
    "msg.placePending": "Your place was submitted for admin review.",
    "msg.placeSaveError": "The place could not be published. Please try again.",
    "msg.serviceSaved": "Service published successfully.",
    "msg.servicePending": "Your service was submitted for admin review.",
    "msg.serviceSaveError": "The service could not be published. Please try again.",
    "msg.permissionDenied": "You do not have permission for this action. Check rules and authentication.",
    "msg.invalidImage": "The image URL is not valid.",
    "msg.imageUploadError": "One or more images could not be uploaded. Check format, size, connection, and Firebase Storage permissions.",
    "msg.imageUploadPartial": "The business was saved, but some images could not be uploaded.",
    "msg.realtimeSync": "Real-time update received.",
    "msg.signInRequired": "You must sign in with Google to publish. If you are not signed in, the publish button will not send data.",
    "msg.firebaseLoadError": "Real-time data could not be loaded.",
    "msg.signInError": "Google sign-in failed.",
    "msg.signInBlockedDomain": "This domain is not authorized in Firebase Auth. Add harinrc.github.io to Authorized domains.",
    "msg.signInPopupBlocked": "The browser blocked the Google popup. Allow popups and try again.",
    "msg.signInPopupClosed": "You closed the sign-in popup before completing the process.",
    "msg.signInOperationDisabled": "Google Sign-In is not enabled in Firebase Authentication.",
    "msg.signInNetworkError": "Network error while signing in. Check your connection and try again.",
    "msg.adminOnly": "This action is for administrators only.",
    "msg.moderationUpdated": "Moderation updated successfully.",
    "msg.moderationError": "Moderation update failed.",
    "msg.editorSaved": "Changes saved successfully.",
    "msg.mapPickStart": "Select the point on the map to save the location.",
    "msg.mapLocationSet": "Location set from map.",
    "msg.mapLocationCleared": "Location cleared.",
    "msg.locationRequired": "You must select a location on the map before publishing.",
    "install.title": "Install Mateare Vivo",
    "install.description": "Add the app to your device so you can open it quickly and use it more comfortably on mobile.",
    "install.descriptionUnsupported": "Your browser does not offer automatic install here, but you can still use the website or open it in a compatible browser to install it.",
    "install.cta": "Install app",
    "install.ctaHelp": "How to install",
    "install.dismiss": "Not now",
    "install.ready": "The app is ready to be installed on your device.",
    "install.success": "Mateare Vivo was installed successfully.",
    "install.unavailable": "Installation is not available in this browser right now. Use Chrome or Edge on Android to see it.",
    "install.unavailableDesktop": "Automatic install is not available in this desktop browser. Use an up-to-date Chrome or Edge.",
    "install.unavailableMobile": "Automatic install is not available in this mobile browser. Try Chrome on Android.",
    "install.iosInstructions": "On iPhone/iPad: open Share and choose \"Add to Home Screen\" to install the app.",
    "install.notSupported": "Your browser already shows this app as installed or does not support installation.",
    "install.notNow": "Okay, I’ll show it again later.",
    "gallery.title": "Preview",
    "gallery.prev": "Previous",
    "gallery.next": "Next",
    "gallery.zoomIn": "Zoom in",
    "gallery.zoomOut": "Zoom out",
    "gallery.reset": "Reset",
    "gallery.close": "Close",
    "gallery.hint": "Tip: you can zoom in and out to see details."
  }
};
