export const initialPlaces = [
  {
    id: "p1",
    name: "Mirador de la Laguna de Xiloa",
    category: "naturaleza",
    description: "Punto panoramico para observar la laguna y tomar fotografias al atardecer.",
    lat: 12.2476,
    lng: -86.3301,
    imageUrl: "https://images.unsplash.com/photo-1537111261222-6b50f4f54f7f?auto=format&fit=crop&w=1200&q=80",
    tags: ["Mirador", "Paisaje"]
  },
  {
    id: "p2",
    name: "Sendero Ecologico Cuajachillo",
    category: "aventura",
    description: "Recorrido guiado por bosque seco tropical con avistamiento de aves.",
    lat: 12.2558,
    lng: -86.4232,
    imageUrl: "https://images.unsplash.com/photo-1482192505345-5655af888cc4?auto=format&fit=crop&w=1200&q=80",
    tags: ["Senderismo", "Aventura"]
  },
  {
    id: "p3",
    name: "Centro Cultural de Mateare",
    category: "cultura",
    description: "Espacio comunitario con expresiones artisticas, danza y gastronomia local.",
    lat: 12.2424,
    lng: -86.4318,
    imageUrl: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80",
    tags: ["Cultura", "Comunidad"]
  }
];

export const initialServices = [
  {
    id: "s1",
    name: "Comedor Dona Martha",
    type: "alimentacion",
    contact: "+505 8888 1234",
    schedule: "7:00 AM - 7:00 PM"
  },
  {
    id: "s2",
    name: "Hostal Brisa de Xiloa",
    type: "hospedaje",
    contact: "+505 8787 6767",
    schedule: "24 horas"
  }
];

export const initialAlerts = [
  {
    id: "a1",
    level: "medium",
    title: {
      es: "Recomendacion de hidratacion",
      en: "Hydration advisory"
    },
    description: {
      es: "Temperaturas altas entre las 12:00 y 15:00. Lleva agua y bloqueador solar.",
      en: "High temperatures from 12:00 to 15:00. Carry water and sunscreen."
    }
  },
  {
    id: "a2",
    level: "high",
    title: {
      es: "Precaucion por lluvias",
      en: "Heavy rain caution"
    },
    description: {
      es: "Posibles lluvias por la tarde en rutas rurales. Verifica el estado de caminos.",
      en: "Possible afternoon rain on rural routes. Check road conditions."
    }
  }
];

export const i18n = {
  es: {
    "nav.home": "Inicio",
    "nav.diagnosis": "Diagnostico",
    "nav.guides": "Guias",
    "nav.register": "Publicar",
    "nav.map": "Mapa y Rutas",
    "nav.moderation": "Moderacion",
    "nav.contact": "Contacto",
    "auth.guest": "Invitado",
    "auth.signIn": "Entrar con Google",
    "auth.signOut": "Salir",
    "auth.required": "Inicia sesion con Google para publicar lugares y servicios.",
    "auth.connectedAs": "Conectado como",
    "auth.firebaseOff": "Modo local activo: completa firebase-config.js para activar Firebase.",
    "hero.tag": "Turismo comunitario en Nicaragua",
    "hero.title": "Descubre Mateare con rutas, guias y servicios locales",
    "hero.description": "Plataforma digital para turistas nacionales y extranjeros que conecta emprendimientos, lugares turisticos poco difundidos y experiencias autenticas en el municipio de Mateare.",
    "hero.primaryCta": "Explorar destinos",
    "hero.secondaryCta": "Publicar emprendimiento",
    "hero.panelTitle": "Estado rapido del destino",
    "hero.weather": "Clima actual",
    "hero.alerts": "Alertas activas",
    "hero.posts": "Publicaciones comunitarias",
    "diagnosis.tag": "Diagnostico territorial",
    "diagnosis.title": "Digitalizar para visibilizar el turismo local",
    "diagnosis.description": "El municipio cuenta con atractivos naturales, cultura viva y emprendimientos gastronomicos, pero su difusion digital es limitada. Este portal centraliza informacion y fortalece la promocion turistica.",
    "diagnosis.card1.title": "Baja promocion",
    "diagnosis.card1.text": "Muchos destinos y servicios no tienen presencia web constante.",
    "diagnosis.card2.title": "Necesidad de rutas",
    "diagnosis.card2.text": "El turista requiere orientacion clara para llegar de forma segura y rapida.",
    "diagnosis.card3.title": "Oportunidad economica",
    "diagnosis.card3.text": "La digitalizacion impulsa emprendedores y dinamiza la economia local.",
    "guides.tag": "Guia turistica dinamica",
    "guides.title": "Lugares recomendados en Mateare",
    "guides.searchLabel": "Buscar",
    "guides.searchPlaceholder": "Ej: Mirador",
    "guides.filterLabel": "Categoria",
    "guides.all": "Todas",
    "guides.nature": "Naturaleza",
    "guides.culture": "Cultura",
    "guides.adventure": "Aventura",
    "weather.tag": "Clima en tiempo real",
    "weather.title": "Consulta el estado climatico",
    "weather.destination": "Destino",
    "weather.refresh": "Actualizar",
    "weather.loading": "Cargando clima...",
    "alerts.tag": "Sistema de alertas",
    "alerts.title": "Informacion util para viajar",
    "alerts.readMore": "Leer noticia",
    "publish.tag": "Registro comunitario",
    "publish.title": "Publica lugares y servicios turisticos",
    "publish.placeTitle": "Registrar lugar turistico",
    "publish.placeName": "Nombre del lugar",
    "publish.placeCategory": "Categoria",
    "publish.description": "Descripcion",
    "publish.placeImageUrls": "URLs de imagen (opcional)",
    "publish.placeImageUrlsPlaceholder": "https://... (una por linea o separadas por coma)",
    "publish.placeImageFiles": "Subir imagenes (opcional)",
    "publish.pickOnMap": "Seleccionar en mapa",
    "publish.clearLocation": "Limpiar ubicacion",
    "publish.locationHint": "Haz clic en \"Seleccionar en mapa\" y luego toca el punto exacto en el mapa.",
    "publish.publishPlace": "Publicar lugar",
    "publish.serviceTitle": "Registrar servicio turistico",
    "publish.serviceName": "Nombre del servicio",
    "publish.serviceType": "Tipo",
    "publish.food": "Alimentacion",
    "publish.lodging": "Hospedaje",
    "publish.activities": "Actividades",
    "publish.contact": "Contacto",
    "publish.schedule": "Horario",
    "publish.serviceImageUrls": "URLs de imagen (opcional)",
    "publish.serviceImageUrlsPlaceholder": "https://... (una por linea o separadas por coma)",
    "publish.serviceImageFiles": "Subir imagenes (opcional)",
    "publish.publishService": "Publicar servicio",
    "publish.feedTitle": "Publicaciones comunitarias",
    "map.tag": "Ubicacion y rutas",
    "map.title": "Mapa interactivo de destinos",
    "admin.tag": "Panel administrativo",
    "admin.title": "Moderar publicaciones pendientes",
    "admin.description": "Aprueba, rechaza o elimina contenido enviado por la comunidad.",
    "admin.pendingPlaces": "Lugares pendientes",
    "admin.pendingServices": "Servicios pendientes",
    "admin.managePlaces": "Gestionar lugares",
    "admin.manageServices": "Gestionar servicios",
    "admin.emptyPlaces": "No hay lugares pendientes por revisar.",
    "admin.emptyServices": "No hay servicios pendientes por revisar.",
    "admin.emptyAllPlaces": "No hay lugares registrados.",
    "admin.emptyAllServices": "No hay servicios registrados.",
    "admin.approve": "Aprobar",
    "admin.reject": "Rechazar",
    "admin.edit": "Editar",
    "admin.delete": "Eliminar",
    "admin.createdBy": "Creado por",
    "admin.statusPending": "Pendiente",
    "admin.statusApproved": "Aprobado",
    "admin.statusRejected": "Rechazado",
    "admin.editorTitle": "Editor administrativo",
    "admin.editorName": "Nombre",
    "admin.editorImages": "URLs de imagenes",
    "admin.editorImageFiles": "Subir imagenes nuevas (opcional)",
    "admin.editorStatus": "Estado",
    "admin.saveChanges": "Guardar cambios",
    "admin.cancelEdit": "Cancelar",
    "footer.text": "Mateare Vivo - Turismo comunitario - Compatible con Android, iOS y Windows",
    "footer.links": "Enlaces rapidos",
    "footer.contact": "Contacto local",
    "footer.contactText": "Promocion turistica comunitaria de Mateare, Managua.",
    "guide.route": "Trazar ruta",
    "guide.more": "Ver en mapa",
    "guide.category": "Categoria",
    "weather.temp": "Temperatura",
    "weather.wind": "Viento",
    "weather.rain": "Lluvia",
    "weather.updated": "Actualizado",
    "weather.error": "No se pudo cargar el clima en este momento.",
    "feed.place": "Nuevo lugar",
    "feed.service": "Nuevo servicio",
    "alert.none": "No hay alertas activas por ahora.",
    "msg.placeSaved": "Lugar publicado correctamente.",
    "msg.placePending": "Tu lugar fue enviado para revision del administrador.",
    "msg.placeSaveError": "No se pudo publicar el lugar. Intenta de nuevo.",
    "msg.serviceSaved": "Servicio publicado correctamente.",
    "msg.servicePending": "Tu servicio fue enviado para revision del administrador.",
    "msg.serviceSaveError": "No se pudo publicar el servicio. Intenta de nuevo.",
    "msg.permissionDenied": "No tienes permisos para esta accion. Revisa reglas y autenticacion.",
    "msg.invalidImage": "La URL de imagen no es valida.",
    "msg.imageUploadError": "No se pudieron subir una o mas imagenes. Verifica formato, tamano, conexion y permisos de Firebase Storage.",
    "msg.realtimeSync": "Actualizacion en tiempo real recibida.",
    "msg.signInRequired": "Debes iniciar sesion con Google para publicar.",
    "msg.firebaseLoadError": "No fue posible cargar datos en tiempo real.",
    "msg.signInError": "No se pudo iniciar sesion con Google.",
    "msg.signInBlockedDomain": "Este dominio no esta autorizado en Firebase Auth. Agrega harinrc.github.io en Authorized domains.",
    "msg.signInPopupBlocked": "El navegador bloqueo la ventana emergente de Google. Permite popups e intenta de nuevo.",
    "msg.signInPopupClosed": "Cerraste la ventana de inicio de sesion antes de completar el proceso.",
    "msg.signInOperationDisabled": "Google Sign-In no esta habilitado en Firebase Authentication.",
    "msg.signInNetworkError": "Error de red al iniciar sesion. Verifica conexion e intenta otra vez.",
    "msg.adminOnly": "Esta accion es solo para administradores.",
    "msg.moderationUpdated": "Moderacion aplicada correctamente.",
    "msg.moderationError": "No se pudo aplicar la moderacion.",
    "msg.editorSaved": "Cambios guardados correctamente.",
    "msg.mapPickStart": "Selecciona el punto en el mapa para guardar la ubicacion.",
    "msg.mapLocationSet": "Ubicacion cargada desde el mapa.",
    "msg.mapLocationCleared": "Ubicacion limpiada.",
    "msg.locationRequired": "Debes seleccionar una ubicacion en el mapa antes de publicar."
  },
  en: {
    "nav.home": "Home",
    "nav.diagnosis": "Diagnosis",
    "nav.guides": "Guides",
    "nav.register": "Publish",
    "nav.map": "Map and Routes",
    "nav.moderation": "Moderation",
    "nav.contact": "Contact",
    "auth.guest": "Guest",
    "auth.signIn": "Sign in with Google",
    "auth.signOut": "Sign out",
    "auth.required": "Sign in with Google to publish places and services.",
    "auth.connectedAs": "Connected as",
    "auth.firebaseOff": "Local mode enabled: fill firebase-config.js to activate Firebase.",
    "hero.tag": "Community tourism in Nicaragua",
    "hero.title": "Discover Mateare with routes, guides, and local services",
    "hero.description": "Digital platform for national and international tourists that connects entrepreneurs, under-promoted attractions, and authentic experiences in Mateare.",
    "hero.primaryCta": "Explore destinations",
    "hero.secondaryCta": "Publish business",
    "hero.panelTitle": "Quick destination status",
    "hero.weather": "Current weather",
    "hero.alerts": "Active alerts",
    "hero.posts": "Community posts",
    "diagnosis.tag": "Territorial diagnosis",
    "diagnosis.title": "Digitize to make local tourism visible",
    "diagnosis.description": "The municipality has natural attractions, living culture, and gastronomy ventures, but digital promotion is still limited. This portal centralizes information and strengthens tourism promotion.",
    "diagnosis.card1.title": "Low promotion",
    "diagnosis.card1.text": "Many destinations and services lack consistent web presence.",
    "diagnosis.card2.title": "Route guidance needed",
    "diagnosis.card2.text": "Tourists need clear orientation to arrive safely and quickly.",
    "diagnosis.card3.title": "Economic opportunity",
    "diagnosis.card3.text": "Digitization boosts entrepreneurs and local economy.",
    "guides.tag": "Dynamic tourism guide",
    "guides.title": "Recommended places in Mateare",
    "guides.searchLabel": "Search",
    "guides.searchPlaceholder": "Ex: Viewpoint",
    "guides.filterLabel": "Category",
    "guides.all": "All",
    "guides.nature": "Nature",
    "guides.culture": "Culture",
    "guides.adventure": "Adventure",
    "weather.tag": "Real-time weather",
    "weather.title": "Check live weather conditions",
    "weather.destination": "Destination",
    "weather.refresh": "Refresh",
    "weather.loading": "Loading weather...",
    "alerts.tag": "Alert system",
    "alerts.title": "Useful travel info",
    "alerts.readMore": "Read article",
    "publish.tag": "Community publishing",
    "publish.title": "Publish attractions and tourism services",
    "publish.placeTitle": "Register tourist place",
    "publish.placeName": "Place name",
    "publish.placeCategory": "Category",
    "publish.description": "Description",
    "publish.placeImageUrls": "Image URLs (optional)",
    "publish.placeImageUrlsPlaceholder": "https://... (one per line or comma-separated)",
    "publish.placeImageFiles": "Upload images (optional)",
    "publish.pickOnMap": "Pick on map",
    "publish.clearLocation": "Clear location",
    "publish.locationHint": "Click \"Pick on map\" and then tap the exact point on the map.",
    "publish.publishPlace": "Publish place",
    "publish.serviceTitle": "Register tourism service",
    "publish.serviceName": "Service name",
    "publish.serviceType": "Type",
    "publish.food": "Food",
    "publish.lodging": "Lodging",
    "publish.activities": "Activities",
    "publish.contact": "Contact",
    "publish.schedule": "Schedule",
    "publish.serviceImageUrls": "Image URLs (optional)",
    "publish.serviceImageUrlsPlaceholder": "https://... (one per line or comma-separated)",
    "publish.serviceImageFiles": "Upload images (optional)",
    "publish.publishService": "Publish service",
    "publish.feedTitle": "Community publications",
    "map.tag": "Location and routes",
    "map.title": "Interactive destination map",
    "admin.tag": "Admin panel",
    "admin.title": "Moderate pending submissions",
    "admin.description": "Approve, reject, or delete content submitted by the community.",
    "admin.pendingPlaces": "Pending places",
    "admin.pendingServices": "Pending services",
    "admin.managePlaces": "Manage places",
    "admin.manageServices": "Manage services",
    "admin.emptyPlaces": "No pending places to review.",
    "admin.emptyServices": "No pending services to review.",
    "admin.emptyAllPlaces": "No places registered yet.",
    "admin.emptyAllServices": "No services registered yet.",
    "admin.approve": "Approve",
    "admin.reject": "Reject",
    "admin.edit": "Edit",
    "admin.delete": "Delete",
    "admin.createdBy": "Created by",
    "admin.statusPending": "Pending",
    "admin.statusApproved": "Approved",
    "admin.statusRejected": "Rejected",
    "admin.editorTitle": "Admin editor",
    "admin.editorName": "Name",
    "admin.editorImages": "Image URLs",
    "admin.editorImageFiles": "Upload new images (optional)",
    "admin.editorStatus": "Status",
    "admin.saveChanges": "Save changes",
    "admin.cancelEdit": "Cancel",
    "footer.text": "Mateare Vivo - Community tourism - Compatible with Android, iOS and Windows",
    "footer.links": "Quick links",
    "footer.contact": "Local contact",
    "footer.contactText": "Community tourism promotion in Mateare, Managua.",
    "guide.route": "Route",
    "guide.more": "See on map",
    "guide.category": "Category",
    "weather.temp": "Temperature",
    "weather.wind": "Wind",
    "weather.rain": "Rain",
    "weather.updated": "Updated",
    "weather.error": "Weather could not be loaded at this time.",
    "feed.place": "New place",
    "feed.service": "New service",
    "alert.none": "No active alerts right now.",
    "msg.placeSaved": "Place published successfully.",
    "msg.placePending": "Your place was submitted for admin review.",
    "msg.placeSaveError": "The place could not be published. Please try again.",
    "msg.serviceSaved": "Service published successfully.",
    "msg.servicePending": "Your service was submitted for admin review.",
    "msg.serviceSaveError": "The service could not be published. Please try again.",
    "msg.permissionDenied": "You do not have permission for this action. Check rules and authentication.",
    "msg.invalidImage": "The image URL is not valid.",
    "msg.imageUploadError": "One or more images could not be uploaded. Check format, size, connection, and Firebase Storage permissions.",
    "msg.realtimeSync": "Real-time update received.",
    "msg.signInRequired": "You must sign in with Google to publish.",
    "msg.firebaseLoadError": "Real-time data could not be loaded.",
    "msg.signInError": "Google sign-in failed.",
    "msg.signInBlockedDomain": "This domain is not authorized in Firebase Auth. Add harinrc.github.io to Authorized domains.",
    "msg.signInPopupBlocked": "The browser blocked the Google popup. Allow popups and try again.",
    "msg.signInPopupClosed": "You closed the sign-in popup before completing the process.",
    "msg.signInOperationDisabled": "Google Sign-In is not enabled in Firebase Authentication.",
    "msg.signInNetworkError": "Network error while signing in. Check your connection and try again.",
    "msg.adminOnly": "This action is for administrators only.",
    "msg.moderationUpdated": "Moderation updated successfully.",
    "msg.moderationError": "Moderation update failed.",
    "msg.editorSaved": "Changes saved successfully.",
    "msg.mapPickStart": "Select the point on the map to save the location.",
    "msg.mapLocationSet": "Location set from map.",
    "msg.mapLocationCleared": "Location cleared.",
    "msg.locationRequired": "You must select a location on the map before publishing."
  }
};
